### ISSUE TITLE
[WARNING] Ignoring metadata for artifact pmd:pmd:pom:SYSTEM as it has duplicate metadata

### ISSUE THREAD

**Issue by HonggangLI** [bennidi/mbassador#136]
While I was building mbassador with maven over Fedora platform, maven emitted some warning messages.

=============
[WARNING] Ignoring metadata for artifact pmd:pmd:pom:SYSTEM as it has duplicate metadata
[WARNING] Ignoring metadata for artifact pmd:pmd:jar:SYSTEM as it has duplicate metadata
[WARNING] Ignoring metadata for artifact pmd:pmd:pom:SYSTEM as it has duplicate metadata
[WARNING] Ignoring metadata for artifact pmd:pmd:jar:SYSTEM as it has duplicate metadata
[WARNING] Ignoring metadata for artifact pmd:pmd:pom:SYSTEM as it has duplicate metadata
[WARNING] Ignoring metadata for artifact pmd:pmd:jar:SYSTEM as it has duplicate metadata
[WARNING] Ignoring metadata for artifact pmd:pmd:pom:SYSTEM as it has duplicate metadata
[WARNING] Ignoring metadata for artifact pmd:pmd:jar:SYSTEM as it has duplicate metadata
[WARNING] Ignoring metadata for artifact pmd:pmd:pom:SYSTEM as it has duplicate metadata
[WARNING] Ignoring metadata for artifact pmd:pmd:jar:SYSTEM as it has duplicate metadata
[WARNING] Ignoring metadata for artifact pmd:pmd:pom:SYSTEM as it has duplicate metadata
[WARNING] Ignoring metadata for artifact pmd:pmd:jar:SYSTEM as it has duplicate metadata
[WARNING] Ignoring metadata for artifact pmd:pmd:pom:SYSTEM as it has duplicate metadata
[WARNING] Ignoring metadata for artifact pmd:pmd:jar:SYSTEM as it has duplicate metadata
[WARNING] Ignoring metadata for artifact pmd:pmd:pom:SYSTEM as it has duplicate metadata
[WARNING] Ignoring metadata for artifact pmd:pmd:jar:SYSTEM as it has duplicate metadata
[WARNING] Ignoring metadata for artifact pmd:pmd:pom:SYSTEM as it has duplicate metadata
[WARNING] Ignoring metadata for artifact pmd:pmd:jar:SYSTEM as it has duplicate metadata
[WARNING] Ignoring metadata for artifact pmd:pmd:pom:SYSTEM as it has duplicate metadata
=============

**Comment by bennidi** [comment]
Thanks for reporting. Will take care of this tomorrow. PMD has been introduced in a PR about two years ago. I never ran into issues but I don't mind removing it (as code style enforcement does not need to be automated in such small projects)

**Comment by bennidi** [comment]
I removed the PMD plugin from the build. Should work fine now. But I am having trouble making the release as I have a new machine and apparently was missing some maven settings so that I am receiving some errors during release. I am currently upgrading the pom.xml to use the nexus-staging plugin but still could not get the release to work. I will get it fixed until Sunday of this week I guess.

**Comment by bennidi** [comment]
Should be fixed now with 1.2.4.2

**Comment by HonggangLI** [comment]
Sorry, but issue persists.

+ cd /builddir/build/BUILD
+ cd mbassador-mbassador-1.2.4.2
+ /usr/bin/python3 /usr/share/java-utils/mvn_build.py --gradle
Executing: gradle-local --no-daemon --offline build xmvnInstall
['gradle-local', '--no-daemon', '--offline', 'build', 'xmvnInstall']
:compileJava
Ignoring metadata for artifact pmd:pmd:pom:SYSTEM as it has duplicate metadata
Ignoring metadata for artifact pmd:pmd:jar:SYSTEM as it has duplicate metadata
Ignoring metadata for artifact pmd:pmd:pom:SYSTEM as it has duplicate metadata
Ignoring metadata for artifact pmd:pmd:jar:SYSTEM as it has duplicate metadata
Ignoring metadata for artifact pmd:pmd:pom:SYSTEM as it has duplicate metadata
Ignoring metadata for artifact pmd:pmd:jar:SYSTEM as it has duplicate metadata
Ignoring metadata for artifact pmd:pmd:pom:SYSTEM as it has duplicate metadata
Ignoring metadata for artifact pmd:pmd:jar:SYSTEM as it has duplicate metadata
Ignoring metadata for artifact pmd:pmd:pom:SYSTEM as it has duplicate metadata
Ignoring metadata for artifact pmd:pmd:jar:SYSTEM as it has duplicate metadata
Ignoring metadata for artifact pmd:pmd:pom:SYSTEM as it has duplicate metadata
Ignoring metadata for artifact pmd:pmd:jar:SYSTEM as it has duplicate metadata
Ignoring metadata for artifact pmd:pmd:pom:SYSTEM as it has duplicate metadata
Ignoring metadata for artifact pmd:pmd:jar:SYSTEM as it has duplicate metadata
Ignoring metadata for artifact pmd:pmd:pom:SYSTEM as it has duplicate metadata
Ignoring metadata for artifact pmd:pmd:jar:SYSTEM as it has duplicate metadata
Ignoring metadata for artifact pmd:pmd:pom:SYSTEM as it has duplicate metadata
Ignoring metadata for artifact pmd:pmd:jar:SYSTEM as it has duplicate metadata
Ignoring metadata for artifact pmd:pmd:pom:SYSTEM as it has duplicate metadata
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
:processResources UP-TO-DATE
:classes
:war
:assemble
:compileTestJavaNote: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

:processTestResources
:testClasses
:test
:check
:build
:xmvnInstall

BUILD SUCCESSFUL

Total time: 1 mins 4.606 secs
+ exit 0

**Comment by bennidi** [comment]
Are you building with gradle?

**Comment by HonggangLI** [comment]
Yes, I was building with grade. I got a fresh clone of mbassador repo on a machine running Fedora 23. And rebuilt it again with maven. It works for me now.
